### ISSUE TITLE
Selectively retrieve results from run*

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#132]
In particular for the CUDA backend, sometimes we want to compute something with `run` but not transfer all/part of the result back to the host.

Perhaps something like `runR :: Arrays a => Acc a ->  Remote a` and then appropriate functions to retrieve the remote array. We also need appropriate unlifting so that we can retrieve only selected components from a tuple of arrays.

The existing `Async` might be able to be adapted to this.

**Comment by mikusp** [comment]
As I was looking for better performance of Accelerate computations, I decided to try and implement this idea. Patch is available here: https://github.com/mikusp/accelerate-cuda/commit/442dd106caa1dca3e61b9c8deb7561d6e133d3e4

It introduces a new data constructor `Remote`. Arrays in Remote are not yet transferred to the host memory. It's done by omitting the collect function after executing a computation on CUDA device. A new function collectRemote is introduced to explicitly transfer result of an operation.

Motivation for this feature is that I've been experimenting with representing array operations as functions `Acc params -> Acc a -> Acc a`, that can be compiled with modified run1 (inspired by your run3 "trick" from accelerate-lulesh). Then, these operations that now have types `params -> a -> a` can be chained using (.). However, transferring the results of each operation back to the host, took a majority of the application runtime. As I only needed to represent functions `a -> Remote a` and `Remote a -> Remote a`, I did not try to implement other variants of run*.

I'm still not sure how this will play with accelerate-cuda internals, particularly with memory management. Transferring part of the result is not relevant to my use case, so I didn't think about "unlifting" Remote through tuples.

While working on this, I also had an idea that goes slightly beyond - would it be possible to use pointers to the device memory instead of transferring the result? In particular, I'm looking for a way to pass the pointers to the results to another running process that would be able to use them and/or transfer memory to host.

**Comment by tmcdonell** [comment]
Ah, thanks for taking a stab at this. I take it that this clears up a lot of the problems that you had, with transferring results back to the host? If so, that is a[nother] good motivation to get this kind of functionality into the library.

As for returning device memory pointers, you may be able to do something like this using the existing Accelerate FFI? It is a slightly different use case to what we have explored already, where we pass device pointers to existing CUDA libraries in the middle of executing an `Acc`, but maybe you can still do it?

**Comment by tmcdonell** [comment]
This now happens transparently in the LLVM-PTX backend, by (once again) abusing Haskell's non-strict evaluation semantics; results are only copied back to the host if they are actually used.

If anybody needs it we could back port to the CUDA backend as well, but otherwise please upgrade to the LLVM-based infrastructure!

Related: #325
