### ISSUE TITLE
Out of memory or something else?

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#247]
*** Internal error in package accelerate ***
    *** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
    ./Data/Array/Accelerate/CUDA/Array/Prim.hs:465:7: (withDevicePtrs): lost device memory #508

Would it be possible to catch an OOM on the GPU, run Haskell GC, and then re-try?

**Comment by robeverest** [comment]
That's exactly what we are currently doing. What you're getting there looks like a bug. Probably one I created when I added the new GC. That is assuming this error comes from HEAD? If so, can you possibly share the code that caused it?

**Comment by yongqli** [comment]
Yes, it is from HEAD. I'm not sure what part of our code is triggering it, but it runs fine for a while and then it is triggered.

**Comment by robeverest** [comment]
Can you possibly run your code with `+ACC -ddump-gc -ACC` so I can get a better idea what was happening when the error was raised? There will be a lot of noise, but if you could just give me the 20 or so lines before the error, it would be helpful.

**Comment by yongqli** [comment]
Actually, I didn't have the last two commits from you. I'll see if I can still reproduce the error, but it might take a while.

**Comment by yongqli** [comment]
Could it be triggered by a foreign CUDA function not executing in the Stream that it was passed in?

What commit did you introduce the GC change? I'll try reverting to that and see if the problem goes away.

**Comment by robeverest** [comment]
I can't see why that would cause that particular error, but there is a good chance the bug is related to foreign functions. 

The new GC was first introduced in 58b6a1f78b0e7e9a6e62f4dea33b56d696e6f4cd for accelerate and AccelerateHS/accelerate-cuda@e13fccdce3dadde0813ad1a2fb9475b6033365d7 for accelerate-cuda. However, there have been numerous other changes since then, so you may find that a bit tricky.

**Comment by yongqli** [comment]
We use `allocateArray` and then fill the pointer with random numbers from `cuRAND`. I'll see if I can produce a small test case.

**Comment by yongqli** [comment]
I'm also not seeing any output from `+ACC -ddump-gc -ACC` -- does profiling have to be on?

**Comment by robeverest** [comment]
No, but accelerate and accelerate-cuda need to compiled with the debug flag turned on.

**Comment by yongqli** [comment]
Could it be caused by threading? It seems that I cannot reproduce the error if I don't have `+RTS -N` turned on.

**Comment by yongqli** [comment]
After running for a long time, I also sometimes encounter a segfault:

    14325.862:gc: malloc: 8 kB
    14325.862:gc: malloc/nursery
    14325.862:gc: insert: Array #527
    14325.862:gc: lookup/found: Array #527
    14325.862:gc: withRemote/using: Array #527
    14325.862:gc: mallocArray: 151 MB
    14325.862:gc: finalise/nursery: Array #527
    14325.862:gc: malloc: 151 MB
    14325.862:gc: finalize cache: Array #527
    14325.862:gc: malloc/nursery
    14325.862:gc: insert: Array #526
    14325.862:gc: finalise/nursery: Array #528
    14325.862:gc: finalize cache: Array #528
    14325.862:gc: lookup/found: Array #526
    14325.862:gc: withRemote/using: Array #526
    [1]    32328 segmentation fault (core dumped)

**Comment by robeverest** [comment]
I think I've managed to recreate this. It does seem to be some sort of a concurrency issue. I'll see if I can figure out what is causing it and let you know. Thanks for the information.

**Comment by robeverest** [comment]
So I've managed to narrow this down a bit and it looks like a couple of problems may have been causing this. I've just pushed a patch that fixes one of them. However, the other problem is more subtle and relates to GHC's garbage collector and is possibly a GHC bug. As a temporary fix, I've found that using GHC's compacting collector with `+RTS -c` seems to make things work. If you're lucky, it won't cause too much of a slowdown.

@mchakravarty Perhaps you can shed more light on this for me. We've talked about this once before, but I think there may be a bug with stable names. Namely that calling `makeStableName` twice on the same object does not always produce the same stable name. I believe it's related to objects being copied during a concurrent GC (it never occurs without `+RTS -N`). Looking at debug messages from the RTS, it seems to happen when `makeStableName` is called on a heap object before and after it has been moved. As I said above, using the compacting collector has made the problem go away for me. However, that could just be a lucky coincidence. It's entirely non-deterministic when it occurs and the smallest example I have is accelerate-nofib. Any further ideas or tips for creating a smaller example?

**Comment by tmcdonell** [comment]
@robeverest instead of using stable names, I've started experimenting with using the raw pointer value instead. These allocations are pinned so won't be moved by the GC, although we do have to be careful in other ways, see note here: https://github.com/AccelerateHS/accelerate-llvm/blob/master/accelerate-llvm/Data/Array/Accelerate/LLVM/Array/Table.hs#L191

There may be other issues with this method I haven't encountered yet, but perhaps that is a way around the problem (and it should be a bit faster).

**Comment by mchakravarty** [comment]
@robeverest Stable names are certainly not guaranteed to produce the same stable name when you run `makeStableName` twice on the same value — as per the `StableName` API spec. Does the GC rely on the stable names always being the same? If so, then that is a flaw in the GC, not a bug in GHC.

@tmcdonell If the objects you are stable naming are not moved by the GC, then I do wonder why they would get different stable names.

**Comment by tmcdonell** [comment]
@mchakravarty My proposal goes directly down to the (pinned) `Addr#`, but currently the stable name is taken on the `ArrayData` constructor (`AD_Int`, `AD_Float` ...) which wraps the `StorableArray` constructor holding the underlying `ForeignPtr`, so probably a couple of those things can be moved by the GC.

**Comment by robeverest** [comment]
@mchakravarty  The GC currently does, and always has, rely on `makeStableName` producing the same stable name if run twice on the same object. The same is true for sharing recovery. Even though the spec does not actually guarantee that to be true, my general understanding has been that stable names were intended to be impervious to moves and copies by the GC. If that weren't the case, then GHC's rts might as well just use pointers into the heap as stable names, rather than keeping them in a table that gets updated every GC. We can work around it in this case, but it's probably something we should keep in mind. 

@tmcdonell I tried what you've done with the LLVM backend and use raw pointer values but ran into a problem, which I think you will as well. When you find a clash between two arrays that both have the same raw pointer value, you call `finalize` on the old array and `yield` to ensure it runs. I found this to be very brittle. When there are multiple concurrent threads, `yield` can wake any of them, so the finalizer is not guaranteed to fire. In fact, I tried calling `performGC` and the finalizer still did not always run before the yielding thread woke up again. You might be able to think of something, but I can't see a way around this.

I have another solution in the unique-arrays branch I just pushed. I didn't want to push it to master as it does introduce a fairly fundamental change. Basically, I generate a unique identifier (just an Int) everytime we construct an array. I considered using Data.Unique for this, but figured a global counter was just as simple and probably faster. What do you think? You might want to also check out my note on finalizers running too soon here: https://github.com/AccelerateHS/accelerate/blob/unique-arrays/Data/Array/Accelerate/Array/Memory/Table.hs#L433

**Comment by mchakravarty** [comment]
>my general understanding has been that stable names were intended to be impervious to moves and copies by the GC. If that weren't the case, then GHC's rts might as well just use pointers into the heap as stable names, rather than keeping them in a table that gets updated every GC. 

Not quite, stable names are a spin of from stable *pointers*. A stable pointer is impervious to GC moves in so far as, given a stable pointer, you are guaranteed to always get back the same Haskell value when dereferencing the stable pointer with `deRefStablePtr` *and*, even if the stable pointer is the sole reference to that Haskell value, it will not be GCed. This is crucial when passing references to Haskell values to foreign functions and motivated the name *stable* pointer.

After we introduced stable pointers as part of the FFI spec, people started to abuse them as a cheap hash values for Haskell values. As a response, the hashing part of stable pointers was factorised out as stable names. Unfortunately, the name wasn't that well chosen, because there is really nothing stable about stable names.

**Comment by yongqli** [comment]
@robeverest, is it possible for you to send me your test case? I'm seeing similar issues on `accelerate 0.15` and am wondering if the issue is related.

**Comment by robeverest** [comment]
@yongqli My test is actually just accelerate-nofib from the accelerate-examples package. The bug is hard to trigger. You need to generate a lot of arrays in a short period of time, if you run accelerate-nofib for long enough with multiple threads, it will usually trigger. However, I wouldn't bother, if I were you. The issue is definitely present in `accelerate-0.15`. 

The good news is I've actually just pushed the changes which I believe fix this bug, so you can try it out and see if it works for you. Let me know if there are any problems.

**Comment by yongqli** [comment]
Looks fixed.
