### ISSUE TITLE
Arrays.flavour is not compatible with custom Arrays instances

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#263]
Here is a problem with the current implementation of 'flavour'. See here from the `linear-accelerate` package, where we want to consider `V3` an array:

https://github.com/tmcdonell/linear-accelerate/blob/dev/accelerate-head/src/Linear/Accelerate.hs#L128

This will compile with HEAD now, except for a missing definition of 'flavour'.

@robeverest can we rework flavour somehow? For example, we get around this for other functions like `arrays` by expressing them in terms of a representation type, should we have an equivalent `FlavourRepr`? Otherwise, should we solve the problem that flavour addresses in a different way, removing the use of flavour altogether? (please remind me what that issue was)

**Comment by rrnewton** [comment]
FYI, that isn't a link to a particular SHA and it appears to be broken.

**Comment by tmcdonell** [comment]
ack, try this: https://github.com/tmcdonell/linear-accelerate/blob/7f290c9c232802be52d8c59bdb9cacc1a5bc108f/src/Data/Array/Accelerate/Linear/V3.hs#L91

**Comment by robeverest** [comment]
Sorry for the late reply on this. Been stuck in bed sick.

The reason `flavour` exists is that for every value in an accelerate program we need to be able to generate code that can access its underlying parts. For example, in the vectoriser, we have something like this

```haskell
liftedReplicate :: Arrays a => OpenAcc aenv a -> OpenAcc aenv (Vector' a)
```

In order to write that function, we need to able to do work for every array contained in `a`. We can convert a value of type `a` into `ArrRepr a`, but not  `OpenAcc aenv a` into `OpenAcc aenv (ArrRepr a)`. We can work with `ProdRepr a` easily enough, via `APrj` and `ATup`, but there's no guarantee that `a` is a product. That's where `flavour` comes in. `flavour` allows us to distinguish between arrays and tuples of arrays dynamically.

The fundamental issue here, as I think I've written somewhere else before, is that we have two systems of representation types in Accelerate, `IsProd` and `Arrays`, neither of which is wholly compatible with the other. Both allow you to convert to and from the representation with raw values, but only with `IsProd` allows  you to project values out of the representation in an AST (`APrj`).

With the `linear-accelerate` library, what I'd usually suggest is to add an `IsProd` instance like so,

```haskell
instance IsProduct Arrays (V3 a) where
  type ProdRepr (V3 a) = ProdRepr (Vector a)
  fromProd p = fromProd p . fromList (Z :. 3) . F.toList
  toProd p t = toProd $ case toList t of
    [a,b,c] -> V3 a b c
    _       -> error "shape mismatch"
```

and then have flavour return `ArraysFTuple`. It's debatable whether it's technically a tuple, as it's only a 1-tuple, but this would allows us to generate code that actually accesses the array inside a value of this type.

Of course, the problem with this is there is already an `IsProduct` instance for V3 that has a conflicting `ProdRepr` definition. This is something that never occurred to me when I added `flavour`. I never thought there would be a case where a user-defined type would need to be used at both the array and scalar level. There might be a possible solution to this, but I haven't thought of it yet. I'll have a look over the next few days.

However, I do wonder why the `Arrays` instance of `V3` exists at all. Without the ability to actually project an array out of it, you can't do anything useful with it in a computation, just pass it around as an opaque value. Do you know why this instance was included in the first place?

**Comment by tmcdonell** [comment]
I'm not sure why the `Arrays` instance for `V3` exists, but when I saw it it occurred to me that `flavour` seems to be preventing the definition of user-defined array types. Maybe that's not a sensible thing to do, like it is with `Elt`, but thought I would bring it up.

It looks like the `linear-accelerate` package was just the `Elt` / `Lift` / `Unlift` definitions. I only just now started lifting the functionality of `linear` into `Exp` terms.

**Comment by fmma** [comment]
How about adding a constructor for converting OpenAcc aenv a into OpenAcc aenv (ArrRepr a)?

    ToArrRepr :: Arrays arrs
              => acc aenv arrs
              -> PreOpenAcc acc aenv (ArrRepr arrs)

**Comment by tmcdonell** [comment]
I think this isn't _really_ an operational problem, it is about getting the right information to the type level. Adding a constructor to the AST seems, unsatisfying...

**Comment by robeverest** [comment]
@tmcdonell As I said before, it doesn't prevent the definition of user-defined array types, you just have to provide an `isProduct` instance. The only time this falls down is when you already have an `isProduct` instance for elt. I think this can be solved by add the constraint as an argument to `ProdRepr`. That would make the two definitions not overlap. However, that is quite a substantial change in order to support what I think is a small edge case. Do you think it's actually worthwhile?

@fmma I agree with Trev that adding yet another constructor to the AST is not the right way we should be solving this. We should should really try to come up with a better way of doing representation types, as talked about in #210. After the FHPC deadline, I might make this a priority. I was planning on addressing #220 first, but I think maybe #210 should come ahead of that.

**Comment by fmma** [comment]
Okay I see you point. I have another crazy idea: How about only allowing user-defined types in the surface language and let the internal AST only be defined on representation types? The transformation to the internal AST (D.A.A.Trafo.Sharing) would then be

    convertAcc
        :: Arrays arrs
        => Acc arrs
        ...
        -> AST.Acc (ArrRepr arrs)  -- Previous: AST.Acc arrs

For tuples, the internal AST would only need constructors for pair and unit. Internal transformation such as lifting to Vector' would only have to work on representation types, which would simplify things a lot including eliminating the need for flavour (I think).

The backends would have to be modified to convert the result back to surface type:

    run :: Arrays a => Sugar.Acc a -> a
    run acc
      = let a = convertAccWith config acc
        in  toArr (evalOpenAcc a Empty)     -- Previous: evalOpenAcc a Empty


Have this been considered before?

**Comment by robeverest** [comment]
I believe @mchakravarty tried this once before, long ago. I don't know what the exact reasons were but I remember him saying that he quickly discovered it was best to delay conversion to representation types for as long as possible.

**Comment by tmcdonell** [comment]
@robeverest I don't think the `V3` case I presented here is justification for such large scale changes. We should just keep this discussion in mind though, if we find a better example in the wild.

@fmma yeah, you can't do it with just representation types.
