### ISSUE TITLE
"Acc (Scalar a)" vs "Exp a"

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#266]
If I have a function which receives parameters, should it accept `Exp a`s or `Acc (Scalar a)`s? What are the performance implications?

**Comment by tmcdonell** [comment]
At a concrete example, let's say that you use these as part of a `map f xs` operation. The `Exp a` will  be evaluated as part of the function `f`, whereas the `Acc (Scalar a)` will be evaluated separately and its result read in from memory.

As for performance, that depends on what these expressions are. Benchmark to find the best choice for your particular application.

**Comment by zgredzik** [comment]
When thinking about performance always keep in mind that:
> a backend that does external code generation may embed this constant directly into the generated code, which means new code will need to be generated and compiled every time the value changes

E.g. when using the cuda backend, if you accept an argument as an `Exp a` instead of  `Acc (Scalar a)` and that argument changes in each consecutive run, each `run` call will recompile the kernel (since the value is treated as a literal in the generated code). This means a single call can drop in performance from a few milliseconds to a few seconds.

Personally, if it's not necessary (the value is not an argument passed from haskell to acc computations but is calculated based on some other intermediate values within the computations), I wouldn't use `Scalar`s. If I understand correctly, using a `Scalar` causes the value to be passed as an argument to a kernel. Using that to implement a simple `add` function, used by some bigger computations, would in my opinion result in that part of computations (just the adding of two values) to be extracted into a separate kernel. That would mean the part of the computations before using the `add` function and after it would end up in another two kernels. Running 3 consecutive kernels instead of one that does exactly the same thing will probably always cause some performance overhead.

As a bonus, here is an implementation of a simple function that I found quite useful, especially when used with view patterns:
```haskell
variable :: (Lift Exp e, Elt (Plain e)) => e -> Exp (Plain e)
variable = the . unit . lift -- (or constant instead of lift - is there actually any difference?)

addScalarToVector :: (Shape sh, Elt e) => e -> Acc (Array sh e) -> Acc (Array sh e)
addScalarToVector (variable -> val) = map (+val)
```
Btw are there any reasons against adding such a function to the accelerate package?

**Comment by yongqli** [comment]
Also useful would be a Haskell array version of `the`: `Array (Scalar a) -> a`

**Comment by zgredzik** [comment]
I don't think that's a valid type, since you can't parametrise arrays with other arrays and `Scalar` is an array. Unless you meant `Scalar a -> a` ;)

**Comment by yongqli** [comment]
Yes, that is what I meant. Thanks.
