### ISSUE TITLE
concatV

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#269]
More a feature request than a bug, but what's the best way to efficiently write this function?

```
-- | FIXME: This is O(n^2)!
_concatV :: (Elt e, Slice sh, Shape sh) => [Acc (Array (sh :. Int) e)] -> Acc (Array (sh :. Int) e)
_concatV arrs =
  foldl1 (A.++) arrs
```

1) Send data back to Haskell and concatenate on CPU to prevent generating a large kernel.
2) Recursively `++` two at a time. I believe this will generate a lot of GPU code?

**Comment by yongqli** [comment]
Woops, it should be `concatH` instead, at least if we interpret the shape as `Z:.row:.col`.

**Comment by tmcdonell** [comment]
Sorry, I forgot to reply to this one.

This is tricky. I don't know if there is a single "best" way to do this.

Fusion might be detrimental here, if it combines functions with very different workloads. You could force everything to be computed first, and then the concat just has do determine where to read data from. The generated code will have many branches, but shouldn't be too bad (the memory reads will be coalesced, and you'll only get warp divergence on the boundaries). A better way _might_ be to do `memcpy` instead of `(A.++)`, but the latter can fuse so maybe will pay off.

```
concatH :: (Elt e, Slice sh, Shape sh) => [Acc (Array (sh :. Int) e)] -> Acc (Array (sh :. Int) e)
concatH
  = P.foldl1 (A.++)
  . P.map A.compute
```

A smarter compiler might be able to tell the individual kernels to write their results into the memory for that combined array (sorta push-array style).
