### ISSUE TITLE
Graphic card memory management

### ISSUE THREAD

**Issue by pmlodawski** [AccelerateHS/accelerate#290]
Hello!

In our application we are allowing user to process images and apply multiple effects on it. 
For performance reasons, matrixes are stored in cache, so user can use them later. The problem is, that once used matrix remain in graphic card memory forever and there is no space for later computations, which ends in errors like `CUDA Exception: Out of memory`.

The problem is, that there is no way to release this graphic card memory, other than making all matrixes lose their scope - simply clean the cache. We cannot do it because we will need this matrixes later.

Here is very simple example which shows this behavior:
```haskell
module Main where

import           Control.Concurrent
import           Data.Array.Accelerate ((:.)((:.)), Z(Z))
import qualified Data.Array.Accelerate      as A
import qualified Data.Array.Accelerate.CUDA as C
import           System.Mem


createMatrix a = A.maximum $ A.map (+a) $ A.use (A.fromList (Z:.100000000) [1..100000000] :: A.Vector Double)


main :: IO ()
main = do
    let x =  createMatrix 5
        -- ^ once this matrix will be computed we will
        --   be unable to remove it from graphic card memory
    putStrLn "run"
    y <- return $ C.run x
    print $ length $ show y
    putStrLn "clean card memory"
    performGC
    C.performGC
    putStrLn "clean exit"
    -- We need `x` in scope, but don't want it to be stuck in graphic card
    -- See on nvidia-smi that x is still occuping memory
    threadDelay 10000000
    print $ length $ show x

```
Is there any way to move this matrixes from graphics card to RAM? This is very important to us

**Comment by pmlodawski** [comment]
I tried also to patch `accelerate-cuda` calling `unsafeFree` on `run` exit, but there is still something stuck in graphic card memory.

**Comment by robeverest** [comment]
So we've been doing some work on out-of-core algorithms similar to the video processing you describe; i.e. streaming datasets larger than the available device memory through the GPU. It's still fairly early days, but we do actually have an experimental feature in HEAD that tries to solve this problem. In essence, if Accelerate is unable to allocate GPU memory it will copy the least recently used array back to host memory and try again. This eviction strategy is not ideal for all possible out-of-core programs, but it works well for streaming ones. If I understand what you're trying to do with your video processing, this strategy would also work well for you, would it not?

I'm not sure your example really highlights the problem very well. `x` would only be 4 bytes in size as it's just a float. If you were to `unsafeFree` it before calling `performGC`, it would be removed from memory, but given it's so small, it's unlikely to make much of a change in overall memory usage. There's a bunch of extra stuff that gets put into GPU memory (contexts, events, compiled programs, etc.) when `run` is called for the first time, so that's probably what you're seeing in memory. 

Have you perhaps got a larger program that actually causes `CUDA Exception: Out of memory` so we can see why the array eviction or perhaps `unsafeFree` is not working properly?

**Comment by pmlodawski** [comment]
Probably this strategy will work for me. I'll try to test it, but it will take some time. I understand that I can still use old API and `CUDA.run`?

Coming back to `x` and it size, you are right - it should be only 4 bytes, but right after `putStrLn "clean exit"` call, `nvidia-smi` shows that whole program use 788MiB graphic card memory. 
```
Wed Nov 18 10:05:52 2015
+------------------------------------------------------+
| NVIDIA-SMI 352.39     Driver Version: 352.39         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 750     Off  | 0000:01:00.0      On |		  N/A |
| 33%   30C    P0     1W /  38W |    870MiB /  2044MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1468    G   /usr/libexec/Xorg                                0MiB |
|    0      1946    G   /usr/libexec/Xorg				62MiB |
|    0      3156    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd     4MiB |
|    0      7675    C   ...4-linux/ghc-7.10.2/lib/ghc-7.10.2/bin/ghc   788MiB |
+-----------------------------------------------------------------------------+
```

**Comment by pmlodawski** [comment]
@robeverest I try to test `streaming` branch but it does not compile. Which `accelerate` and `accelerate-cuda` versions will work together?

**Comment by robeverest** [comment]
@pmlodawski The large memory usage you're seeing is actually the array being `use`d in create matrix. If your last line were to read `print $ length $ show y`, you should see it disappear.

You don't actually need to use the `streaming` branch. All the latest memory management stuff is in `master`.

**Comment by pmlodawski** [comment]
It looks like new accelerate version is much better in memory management. Closing, thanks!
