### ISSUE TITLE
Is there a way to choose GPU?

### ISSUE THREAD

**Issue by xinhuazhang** [AccelerateHS/accelerate#294]
Hi,

Suppose I have more than one GPU in a machine, can I use which one to use?

Thanks

**Comment by tmcdonell** [comment]
Yes, you can.

Instead of `run`, use `runWith`, and instead of `run1`, use `run1With`, etc. These `*With` functions take an extra argument which is the execution context to use, and just like in plain CUDA C the execution context is specific to a device.

You can create an `accelerate-cuda` compatible `Context` with `create` or `fromDeviceContext` (which are also exported from `Data.Array.Accelerate.CUDA`. These will require some interaction with the lower level CUDA bindings package; [check the documentation there for more information and a short tutorial](https://hackage.haskell.org/package/cuda-0.7.0.0/docs/Foreign-CUDA-Driver.html).

```haskell
import Data.Array.Accelerate.CUDA
import qualified Foreign.CUDA.Driver as CUDA

acc :: Acc (Vector Int)
acc = ...

main :: IO ()
main = do
  CUDA.initialise
  dev <- CUDA.device 1               -- CUDA devices are enumerated starting at 0
  ctx <- create dev []               -- 'create' here comes from accelerate-cuda, not cuda
  ...
  let result = runWith ctx acc
  ...
```

Hope that helps. Let me know if you have any other questions. I guess I should write this up in the main documentation as well...

**Comment by xinhuazhang** [comment]
Using Multiple GPUs is gonna be a trend I think. Amazon ec2 provides a 4 GPUs instance which is powerful. Thank you : )
