### ISSUE TITLE
Adding HList support

### ISSUE THREAD

**Issue by schernichkin** [AccelerateHS/accelerate#295]
Greetings. I'm attempting to add HList support to Accelerate and I can't figure out how to implement Unlift instance for HList. Here is my attemp: https://gist.github.com/schernichkin/df3745a0b68f7c32ef15

I've implemented Elt and IsTuple (L41-L64), then I created Lift instance (L75 - looks scary, but seems to work), and finally I'm trying to write Unlift (L92) which should map Exp (HList '[a, b, ...]) to HList '[Exp a, Exp b, ...] I've figured out how to peek first item from the tuple with ZeroTupIdx `Prj` e but I have no idea how to deal with the tail of the list. I can't find any relevant examples, so could someone take a brief look at my code and point me right direction? 

Thanks.

**Comment by robeverest** [comment]
With a little bit of playing around I got it to work like this.

https://gist.github.com/robeverest/925da3ef99bd9f021a9d

The main change was in the tuple representation. Rather than the list `[a,b,c]` having `a` at tuple index 0, `b` at 1 and `c` at 2, instead `a` is at 0 and `[b,c]` is at 1. Essentially giving HLists the more natural representation of a pair of head and tail.

Overall, I'm not sure how useful this really is. All the constraints on the lift and unlift instances would make it very hard to work with `HLists` in a generic fashion, but I don't know how you intend to use this.

**Comment by schernichkin** [comment]
Thank you for help. As for your question: I'm trying to port Frames (https://hackage.haskell.org/package/Frames) to Accelerate. It already has in-memory engine (called Frames.InCore), I think it could be interesting to have Accelerate support as well.

**Comment by schernichkin** [comment]
I did more exploration and created small demo app: https://github.com/schernichkin/frames-accelerate/blob/master/demo/Main.hs I had no opportunity to check it with real back-end because I don't have CUDA device, but it seem to work fine with accelerate interpreter, and with lenses, constraint kinds and litte bit of TH it allows to use HLists in generic way almost without boilerplate. I think this issue can be closed now.

**Comment by tmcdonell** [comment]
(closing as requested)
