### ISSUE TITLE
cabal install accelerate-examples reports LLVM version problem (accelerate-canny)

### ISSUE THREAD

**Issue by jwaldmann** [AccelerateHS/accelerate#298]
I am building accelerate-examples-0.15.1.0 with ghc-7.10.3 on fedora 23, and get
```
Preprocessing executable 'accelerate-canny' for
accelerate-examples-0.15.1.0...
[1 of 4] Compiling Config           ( examples/canny/src-acc/Config.hs, dist/build/accelerate-canny/accelerate-canny-tmp/Config.o )
You are using a new version of LLVM that hasn't been tested yet!
We will try though...
opt: /tmp/ghc4734_0/ghc_2.ll:7:6: error: unexpected type in metadata definition
!0 = metadata !{metadata !"top", i8* null}
     ^
Failed to install accelerate-examples-0.15.1.0
```
I figure this might be a cabal/ghc problem. But still - how do you compile this? Do I need to build some obsolete llvm? (FC 23 has 3.7.0) How do I tell cabal-install/ghc where it is? Do I need it at all? accelerate-examples.cabal has flags llvm-cpu/llvm-gpu, off by default, but the section for Executable accelerate-canny has -fllvm unconditionally.

**Comment by jwaldmann** [comment]
Ah! I got it to work on FC 21, which has llvm-3.5. I need to edit ghc's settings file,
which is in $PREFIX/lib/ghc-7.10.3/settings .

**Comment by tmcdonell** [comment]
That error is coming from GHC itself, as it tries to compile standard Haskell code via LLVM (because of the `-fllvm` flag) instead of its built-in native code generator. This is well before anything gets touched by `accelerate-llvm`. I can't recall which versions of LLVM that GHC supports, but I expect somebody on the haskell-cafe mailing list would know, and/or be in a position to start supporting newer versions.

The version of LLVM that `accelerate-llvm` uses is limited to what is supported by `llvm-general`, currently up to 3.5.

I can't do anything about the cuda toolkit unfortunately.
