### ISSUE TITLE
Compatible commits for accelerate, accelerate-cuda, and accelerate-llvm?

### ISSUE THREAD

**Issue by o1lo01ol1o** [AccelerateHS/accelerate#320]
Is there any known configuration of commits that has these three building nicely?  My current stack:

```
- location:
    git:    https://github.com/AccelerateHS/accelerate.git
    commit: aed12138a9788ff5d6289d214c84ff6108dc04bd
  extra-dep: true
- location:
    git: https://github.com/AccelerateHS/accelerate-cuda
    commit: 05acd3adca9fd89a8ac19184afbed47d1b7d1505
  extra-dep: true
- location:
    git:    https://github.com/AccelerateHS/accelerate-llvm.git
    commit: 987bff46f146b718a1da60c194eceff4b91a843f
```

can't build accelerate-llvm:

```
Ambiguous occurrence ‘BitSize’
        It could refer to either ‘LLVM.General.AST.Type.Bits.BitSize’,
                                 imported from ‘LLVM.General.AST.Type.Bits’ at LLVM/General/AST/Type/Instruction.hs:19:1-33
                                 (and originally defined at LLVM/General/AST/Type/Bits.hs:31:1-28)
                              or ‘Data.Array.Accelerate.Type.BitSize’,
                                 imported from ‘Data.Array.Accelerate.Type’ at LLVM/General/AST/Type/Instruction.hs:24:1-33

```

And trying to use combinations of the commits in the package-respective stack.yaml files hasn't yet yielded a configuration that will build.

Do I have to go back to the hackage packages?

**Comment by tmcdonell** [comment]
Yeah, I know this is a problem. I'm currently working on something to try and keep everything synced and building together (or, at least notify me when it doesn't). Stay tuned...

However, I thought that `accelerate-cuda` and `accelerate-llvm` at least were up-to-date with base `accelerate`. hmm...

Oh, turns out I hadn't pushed my branch upstream. Try https://github.com/AccelerateHS/accelerate-llvm/commit/2c26ca7755a3f5acc3a56dd0f4a23565ba620501. (Ignore the failing travis, it is because llvm.org turned off their apt repositories and I haven't transitioned to something else yet).

**Comment by o1lo01ol1o** [comment]
Great, they seem to be building now. Thanks!
