### ISSUE TITLE
Design advice for general linear algebra operations using accelerate & co

### ISSUE THREAD

**Issue by o1lo01ol1o** [AccelerateHS/accelerate#321]
I've been working on adding an accelerate backend to SubHask (without initially knowing anything about either) and I wondered if someone could advise on some design decisions.   I had I thought that I would just be able to define, e.g., A Vector type based on a DIM1 accelerate array then assign it to the appropriate instances and create the appropriate operator overrides.  However I haven't been able to figure out the appropriate lifting patterns to keep the instances happy and, I'm not totally sure the results wouldn't create some nested parallelism due to some operators returning Acc.

You can see some of the awful dancing I've been trying [here.](https://github.com/o1lo01ol1o/subhask/blob/c29180f8d1d0ad13f915b36a9de8f255c8f3365d/src/SubHask/Algebra/Accelerate/Vector.hs#L46) 

Last night I managed to find https://github.com/tmcdonell/linear-accelerate and based on the inline comments it seems I should either design around an Acc Array type or an Exp type and only lift in and out of that type.  Is this accurate?  What are the performance implications?  

Are there any other resources floating around I could use to get some ideas (I've gone through the papers and slides listed on the wiki; those are helpful for implementing such-and-such algorithm in acclerate but less so for this task.)

**Comment by tmcdonell** [comment]
I don't know anything about Subtask, but just at a glance it looks like wants to operate over arrays, so designing around `Acc` is probably the way to go.

For the linear-accelerate this was more about operations on short fixed-length vectors (`V3`, `V4`, etc...), which was more suitable for `Exp`. In my use case for `linear-accelerate` I also wanted arrays of these things (e.g. arrays of positions in 3D space).

This process can be a bit tricky, so feel free to keep asking questions. I'm quite interested to see this progress so will help where possible.

**Comment by o1lo01ol1o** [comment]
Ok, that's what I had been doing but then started to wonder if that wasn't the best way to handle constructing the computation graph.

I'll do another pass with that in mind and post back if (when) I have questions.

Thanks.

**Comment by o1lo01ol1o** [comment]
Ok, a couple API questions:  What's the `LLVM` equivalent of `CUDA.run`?  Is it possible to (and if so is there any information on) how to use `CUDA` streams for batch-like computations?

**Comment by tmcdonell** [comment]
- You'll need to install one of the llvm-backends: `accelerate-llvm-native` for multicore cpu, or `accelerate-llvm-ptx` for NVIDIA GPUs. Those will contain the usual `run*` functions.

- What do you mean by batch-like operations? Internally we'll launch kernels in separate streams so that the operations can execute concurrently, but that isn't something you can explicitly control.

**Comment by o1lo01ol1o** [comment]
Thanks, didn't remember those packages were included as deps.
 
Re "Batch operations", I meant something like streaming a dataset to a given computational kernel or kernels.  (Maybe this is straight-forward and I just haven't stumbled upon the code in the api that controls it.)  

(On a related note, are there any examples of keeping a kernel compiled on a device for an arbitrary amount of time so that the kernel could be deployed as part of micro-service --  say, via servant or yesod?  Forgive me if this is also a simple case that becomes evident with more accelerate use, I'm just trying to keep things straight down the line.)  

Thanks for your help!

**Comment by tmcdonell** [comment]
You should try [`run1`](https://github.com/AccelerateHS/accelerate-cuda/blob/master/Data/Array/Accelerate/CUDA.hs#L276) or [`stream`](https://github.com/AccelerateHS/accelerate-cuda/blob/master/Data/Array/Accelerate/CUDA.hs#L337) (and their variants). These will do extra caching behind the scenes to make sure calling the function multiple times avoids unnecessary overheads. I use this in the [`accelerate-examples`](https://github.com/AccelerateHS/accelerate-examples) package, where for example each frame of an animation is done via a call to `run1` to avoid front-end conversion/optimisation/compilation stages at each frame. Your setup sounds a bit different (and I'm not familiar with how servant or yesod operate), but maybe that will work for you also.

Note that the cuda backend will always keep compiled kernels on disk so that they can be reused later, but `run1` gets you quite a bit further.
