### ISSUE TITLE
stack install accelerate-cuda failing

### ISSUE THREAD

**Issue by allenj12** [AccelerateHS/accelerate#332]
when trying to install accelerate-cuda through stack I get this error

http://pastebin.com/2xLgZZGc

**Comment by tmcdonell** [comment]
You need to:

> stack setup --upgrade-cabal

This is because my [cuda](https://github.com/tmcdonell/cuda/) package has a custom `Setup.hs` script, but cabal has no way of testing what version of the library you are compiling the `Setup.hs` file with (although that is changing, so things should improve). This is mentioned in the docs for that package.

**Comment by allenj12** [comment]
Alright sorry about that. Now I am getting this however http://pastebin.com/kavbGvUM , I followed the instructions on the wiki. I installed cuda through arch's pacman, and set the paths (which for me is /opt/cuda/...' however for the ld_library_path I only seem to have a 'lib64', no 'lib'.

**Comment by tmcdonell** [comment]
Ah, are you using cuda-8? I haven't finished updating the package for that yet. You can try using [this branch](https://github.com/tmcdonell/cuda/tree/feature/8.0), which I haven't finished yet but it should at least compile. In the packages section of your `stack.yaml` something like...

```
- location:
    git:    https://github.com/tmcdonell/cuda.git
    commit: 5006e0dec15c18e925caf7b8499d657c50f6cb3f
  extra-dep: true
```

**Comment by tmcdonell** [comment]
I made a patch release which should fix your issues.
https://hackage.haskell.org/package/cuda-0.7.5.1
