### ISSUE TITLE
Malloc error

### ISSUE THREAD

**Issue by grafvetkindorff** [AccelerateHS/accelerate#341]
Hi

I tried to make vector with 1e8 Int elements:

```haskell
radixsort_test = radixsort_descending CUDA arr
  where arr = fromList (Z:.100000000) [1..] :: Vector Int
```

where radixsort_descending:

```haskell
radixsort_descending backend xs = toList (run1 backend (radixsortBy complement) xs)
```

(i got these pieces of code from accelerate-examples)

and... :

```
$ ./.stack-work/install/x86_64-linux/lts-7.8/8.0.1/bin/rsort-exe
rsort-exe: 
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/Array/Remote/LRU.hs:237:40: (malloc): Remote memory exhausted
CallStack (from HasCallStack):
  error, called at ./Data/Array/Accelerate/Array/Remote/LRU.hs:237:40 in accelerate-1.0.0.0-Is1nAdB6bTvHQlnF4R89kI:Data.Array.Accelerate.Array.Remote.LRU
```

With 1e7 elements works fine.

**Comment by grafvetkindorff** [comment]
note: used backend is CUDA

**Comment by tmcdonell** [comment]
This is probably just a plain old out-of-memory error. How much memory does your GPU have?

You'll notice that the sample radix sort implementation in `accelerate-examples` is not very efficient (one-bit at a time, uses many intermediate arrays). If your application makes heavy use of sorting then we should use the FFI to call into an optimised library implementation.

You could also try the `accelerate-llvm-native` backend to run on the CPU, since you should have much more memory available.

**Comment by grafvetkindorff** [comment]
GeForce GTX 950: 2GB, and ~300MB used by xorg.
Yes, I think you're right, thanks for answer. I will focus on working with FFI, CPU backend is very slow.

**Comment by tmcdonell** [comment]
The (built in) Interpreter backend is indeed slow, but [`accelerate-llvm-native`](https://github.com/AccelerateHS/accelerate-llvm) produces vectorised multicore CPU code and is pretty good.

By the way, I'd also recommend switching to the `accelerate-llvm-ptx` backend when you can, rather than using `accelerate-cuda`.

Feel free to open a new ticket to discuss how to use the FFI, etc.
