### ISSUE TITLE
LLVM or CUDA

### ISSUE THREAD

**Issue by Qinka** [AccelerateHS/accelerate#351]
We use accelerate-llvm-ptx to avoid using cuda-sdk, for we think cuda's sdk is not easy to install. But when using Windows, I find that the cuda's sdk is easier to install then llvm.  But is accelerate-cude under the maintaining? And when I installed accelerate-llvm-ptx, I still need to install cuda's sdk. Will there be a non-just-in-time backend for cuda/native?

**Comment by tmcdonell** [comment]
1. Right, installing LLVM could be a problem, in particular because we require the llvm shared library so that we can use GHCi/TemplateHaskell, and that might not be part of a given binary distribution. I don't know if there is anything we can do to improve that, but if you have any ideas we could try let me know. I know that the apt packages for Ubuntu/Debian, and Homebrew on macOS include it, but I'm not familiar with the packaging system on Windows (sorry). It does apparently work on Windows though (I don't personally have a Windows machine to test with, but [see here](https://github.com/AccelerateHS/accelerate/pull/342#issuecomment-274116175)), so maybe @awson or @RyanGlScott could provide some tips if you are getting stuck.

2. I am not actively maintaining `accelerate-cuda`, due to lack of time. There are problems with its code generation method with Windows/MSVC, though the relevant tickets (#234, #318, #331) have a solution you could try. It also appears to not be building on ghc-8.0.2 (#335). All of those tickets affect the code generator, which is perhaps the largest and most fragile component (and, this fragility is part of why I moved to the type-safe approach used in `accelerate-llvm`).

3. Right, the CUDA SDK includes the driver software and everything required to talk to the GPU, which we interface with via the FFI binding library `cuda`, used by both `accelerate-cuda` and `accelerate-llvm-ptx`.

4. I have indeed been thinking about how we could do ahead-of-time compilation for Accelerate programs. The `run1` trick is useful, but can be difficult to use and is not always enough. I don't expect to have anything ready soon, however...

**Comment by tmcdonell** [comment]
R.E. (2), I would of course be happy to accept patches for `accelerate-cuda` and to assist people getting up to speed with the code base, I just don't have the time to work on it myself at the moment.
