### ISSUE TITLE
Errors in accelerate-examples with llvm backend

### ISSUE THREAD

**Issue by alang9** [AccelerateHS/accelerate#359]
I've tried running some of the example programs with the llvm-ptx backend, but they always fail with this error:

```
'sm_52' is not a recognized processor for this target (ignoring processor)
'+ptx41' is not a recognized feature for this target (ignoring feature)
'sm_52' is not a recognized processor for this target (ignoring processor)
'sm_52' is not a recognized processor for this target (ignoring processor)
'+ptx41' is not a recognized feature for this target (ignoring feature)
'sm_52' is not a recognized processor for this target (ignoring processor)
accelerate-canny: 
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/LLVM/PTX/State.hs:50:9: (unhandled): CUDA Exception: no kernel image is available for execution on the device
ptxas application ptx input, line 6; error   : PTX .version 3.2 does not support .target sm_52
ptxas fatal   : Ptx assembly aborted due to errors
```

llvm-cpu also fails:
```
accelerate-canny: forkOS_entry: interrupted
accelerate-canny: forkOS_entry: interrupted
accelerate-canny: forkOS_entry: interrupted
accelerate-canny: forkOS_entry: interrupted
accelerate-canny: forkOS_entry: interrupted
accelerate-canny: forkOS_entry: interrupted
accelerate-canny: forkOS_entry: interrupted
accelerate-canny: forkOS_entry: interrupted
accelerate-canny: forkOS_entry: interrupted
```

interpreter and cuda seem to work fine. I'm using llvm-3.5 and cuda-8.0

**Comment by tmcdonell** [comment]
I suspect that the PTX backend errors (`sm_52 ..` and `ptx41 not recognised`) are because the version of LLVM you are using is too old to know about this more recent GPU that you have.

Try updating to LLVM-3.8 or LLVM-3.9 (off hand I'm not sure if 3.8 will work, but 3.9 definitely should). You'll need to update the `stack.yaml` file to point to the appropriate version of `llvm-general`, e.g. by uncommenting the appropriate line [here](https://github.com/AccelerateHS/accelerate-examples/blob/master/stack-8.0.yaml#L63).

You could also try compiling `accelerate-llvm-ptx` with the `nvvm` flag set to `True`. That is a little more speculative, but the last time I tried the combination of LLVM-3.5+CUDA-8.0+NVVM did work. You might run into other problems though so I don't really recommend this...

The `forkOS_entry` errors are annoying but benign. Those threads didn't get to run their finalisers before the whole program shut down and cleaned up their resources anyway. It is annoying, but not harmful, and so far I haven't found a way to suppress the message.

Hope the suggestions help; let me know how it goes.

**Comment by alang9** [comment]
Ah the README here shows an X for llvm-3.9 with cuda-8.0: https://github.com/AccelerateHS/accelerate-llvm/blob/master/README.md

Is it just out of date?

**Comment by tmcdonell** [comment]
Oh, that only if you try to use the NVVM component. LLVM-3.9 itself (without NVVM) is able to work with CUDA-8.0.

Sorry, I'll try and clarify the README.

**Comment by alang9** [comment]
I tried with llvm-3.8, but I now get a different error:

```accelerate-canny: unhandled function attribute enum value: FunctionAttributeKind 3```

**Comment by tmcdonell** [comment]
okay, I think that means your device needs LLVM-3.9. I saw this [before](https://github.com/AccelerateHS/accelerate/issues/350#issuecomment-275648280) and at least in that case moving to LLVM-3.9 fixed it.

(sorry for the hassle)

**Comment by alang9** [comment]
I'm happy to report that everything seems to work with llvm-3.9 =)

For my application, it looks like it's an order of magnitude slower than using hmatrix in haskell, but I guess that's a different issue.

Thanks for the help,
Alex

**Comment by tmcdonell** [comment]
Great! Glad we could get it working (:

Yeah, I really need to write a proper matrix library, which uses cuBLAS and other optimised implementations. There is never enough time for everything... \:
