### ISSUE TITLE
fold comment

### ISSUE THREAD

**Issue by alang9** [AccelerateHS/accelerate#360]
In this comment for `fold`, shouldn't this say outermost, not innermost?

```
-- | Reduction of the innermost dimension of an array of arbitrary rank.  The
-- first argument needs to be an /associative/ function to enable an efficient
-- parallel implementation. The initial element does not need to be an identity
-- element of the combination function.
```

**Comment by tmcdonell** [comment]
I think innermost is correct. But, to be fair, we may have also been a bit inconsistent with the terminology, so do flag these things when you spot it, I really do appreciate that.

What I mean when I say innermost, is for some index/shape `(Z :. a :. b :. c)` then `c` here is the innermost dimension. This is because, in memory, the element at that index will be adjacent to the element at `(Z :. a :. b :. c+1)`, so if we were writing this as a set of nested for-loops in C, then the loop over index `c` would be the "innermost" loop.

At least... that is the way that I think about it. Does that make sense? Feel free to disagree!

**Comment by alang9** [comment]
I see. I think the comment for `indexHead` is wrong then?

```
-- | Get the outermost dimension of a shape
--
```

I think I was confused for this reason. `a` appears to be "innermost" because it requires the most calls to `indexTail` to get to.

**Comment by tmcdonell** [comment]
Yes, that comment is incorrect. I can see the confusion. I will fix the docs, and try to add a better explanation for innermost vs. outermost. Thanks for pointing this out!
