### ISSUE TITLE
Could a Dockerhub image be made available for trying accelerate-llvm-native?

### ISSUE THREAD

**Issue by rrnewton** [AccelerateHS/accelerate#370]
Hi Accelerate devs,

I wanted to kick the tires a bit on the exciting new 1.0 release.  I immediately ran into some minor problem on Ubuntu 16.10 w/ installing LLVM 4.0.  I'm sure its fixable but it will be >0 time to do it.

Now that Accelerate is fully usable without a GPU, can there just be a simple Docker image on dockerhub to allow trying out Accelerate with a one-liner?  I.e.:

```
docker run -it accelerate/accelerate:1.0
```

**Comment by tmcdonell** [comment]
That sounds like a good idea. I have no idea how to setup / properly use docker images though, so some advice/pointers/pull requests would be welcome.

Make sure you have installed a recent gcc. A possibly similar linker issue in #368 was fixed by upgrading to gcc-6.

**Comment by rrnewton** [comment]
@tmcdonell just put the following in a Dockerfile and run `docker build -t accelerate/accelerate .` in the directory containing it:

```
FROM ubuntu:16.10
RUN apt-get -y update && \
    apt-get install -y gcc
```

Then that has gcc 6:

```bash
$ docker run -it accelerate/accelerate gcc --version
gcc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005
```

If you can just add to that the standard Ubuntu commands for installing llvm 4, that would be a good start.  It is *normally* easier to start with `fpco/stack-build:lts-8.8` as a base image, but in this case that will give us Ubuntu 16.04 and GCC 5.4.  So maybe it is better to start with base ubuntu and install stack/ghc on top of that.

**Comment by tmcdonell** [comment]
I set up https://hub.docker.com/r/tmcdonell/accelerate-llvm/ as an automated build, and it should be building now (I have no idea how long until it is ready though). It will set up and install `accelerate-llvm-native` with stack, so it'll be available with `stack exec ghci` for example. Let me know if that is working for you.

**Comment by tmcdonell** [comment]
Okay, so you should now be able to:

```
docker run -it tmcdonell/accelerate-llvm
```

and it will drop you into a shell where accelerate has been installed via stack. If you have a compatible OS and install the [NVIDIA docker](https://github.com/NVIDIA/nvidia-docker) plugin you should be able to run the GPU backend from the container as well (but, I haven't been able to try this yet).

There is also:

```
docker run -it tmcdonell/accelerate-examples
```

Which also has all the example programs. Turn out running OpenGL through containers is tricky though, so at the moment the GUIs are disabled, but you can run the benchmarks or other text-based interfaces, depending on the program.

Let me know if this is useful, or it should be set up differently (e.g. install globally with cabal, rather than in the local stack sandbox?) or if you have other suggestions for how docker should be used...
