### ISSUE TITLE
isNaN and isInfinite broken for 32-bit floats / Native

### ISSUE THREAD

**Issue by VorpalChoices** [AccelerateHS/accelerate#407]
`isNaN ` and `isInfinite` are broken for 32-bit floats with LLVM.Native, at least on macOS and Ubuntu, and I'd expect on Windows too. Looking into it, this is because they're calling library functions specified at Data.Array.Accelerate.LLVM.CodeGen.Intrinsic:53 as:

```
      others
          = ("isnanf", "isnan")
          : ("isnand", "isnan")
          : ("isinff", "isinf") 
          : ("isinfd", "isinf")
          : []
```

On 64-bit platforms `isnan` and `isinf` expect 64-bit calls, but they're getting 32-bit ones. The naming of the correct functions to call depends on the libc present (as far as I can tell, on Linux with glibc the NaN functions are `isnanf` and `isnan` for floats and doubles; on macOS they're `__isnanf` and `__isnand` / `isnan`, and on Windows they're `_isnanf` and `_isnan` / `isnan`).

The simplest fix is to add conditional compilation, but perhaps it would be better to just implement `isnan` and `isinf` internally with LLVM primitives? Let me know what you think and I'll have a go at implementing it.

**Comment by tmcdonell** [comment]
Hey, well caught!

It looks like `isnan` would be easy enough to implement ourselves as `x != x`, so we should probably do that. For`isinf` there is should be a similarly easy thing we can do as well. If we can it with just LLVM primitives that is probably best. (I'm actually kind of surprised this worked at all, it seems like these are just #defines, so I'm not sure what LLVM is picking up here).

(Part of the weirdness here is that these functions get renamed for the PTX backend, but since they should be fully IEEE compliant, what we do for the above should work here too)

**Comment by tmcdonell** [comment]
Thanks for the patch! I also added your example from the PR to the test suite to prevent us breaking this again in the future (:
