### ISSUE TITLE
1.3.0.0 Release

### ISSUE THREAD

**Issue by TravisWhitaker** [AccelerateHS/accelerate#444]
It's been about a year since the last release and there are a bunch of improvements on HEAD. It'd be nice to have a 1.3.0.0 release on Hackage.

I'd be happy to help unbreak things in Nixpkgs and Stackage as well.

@tmcdonell any outstanding issues you'd view as blocking a 1.3.0.0 release?

**Comment by tmcdonell** [comment]
Yes, I agree. I should be able to do this after my current deadline (so maybe early October).

Things to look into:
 - [ ] https://github.com/AccelerateHS/accelerate-llvm/issues/45 @JoshMeredith 
 - [ ] https://github.com/AccelerateHS/accelerate-llvm/pull/48 @ivogabe 
 - [ ] https://github.com/AccelerateHS/accelerate/issues/436 (mostly good to go?)
 - [x] https://github.com/AccelerateHS/accelerate/issues/443 (apparently already fixed in HEAD)
 - [ ] Fix reading and writing for non-power-of-two SIMD vectors
 - [ ] Some packages might still need to be updated to add pattern synonyms; I think `colour-accelerate` is missing them. It might also be worthwhile considering how that package interacts with `accelerate-io-JuicyPixels`.

Anything which should be added to this list?

**Comment by tmcdonell** [comment]
I haven't forgotten about this, I just got swamped with other work, sorry...

**Comment by tmcdonell** [comment]
List of packages to update/upload. Due to a pre-emptive version bump we are currently at 1.4, so I'll just rename them as 1.3 on the release branch and master will remain at 1.4.

- [ ] accelerate
- [ ] accelerate-llvm
- [ ] accelerate-io
- [ ] accelerate-bignum
- [ ] accelerate-blas
- [ ] accelerate-examples
- [ ] accelerate-fft
- [ ] accelerate-io
- [ ] colour-accelerate
- [ ] containers-accelerate
- [ ] gloss-accelerate
- [ ] gloss-raster-accelerate
- [ ] hashable-accelerate
- [ ] lens-accelerate
- [ ] linear-accelerate
- [ ] mwc-random-accelerate
- [ ] cuda
- [ ] nvvm
- [ ] cublas
- [ ] cufft
- [ ] cusparse
- [ ] cusolver

**Comment by tmcdonell** [comment]
https://github.com/AccelerateHS/accelerate/releases/tag/v1.3.0.0 🎉

**Comment by tmcdonell** [comment]
Also I apologise that this took such a long time to complete >.<

**Comment by TravisWhitaker** [comment]
But it was well worth the wait IMO for `match` to make it in!
